---
- name: "Configure Flatpak Remotes"
  hosts: localhost
  connection: local

  tasks:

    - name: Manage flathub Repository
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: system
      become: yes
      tags:
        - packages
        - flatpak


